name: Build on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release tag
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up QEMU for cross-platform builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          apanta123/japan-moller-test:latest
          apanta123/japan-moller-test:${{ github.ref_name }}
